-- Added for ros_common.vessel_identification_licensed_target_species.licensed_target_species_code
-- INSERT INTO refs_biological.species (code, name_en, name_fr, name_scientific, species_group_code, species_category_code, family, "ORDER", iucn_status_code, is_iotc, is_target, is_ssi, is_predator, is_bait, is_aggregate, is_asfis, description_fr, description_en) VALUES ('ABL', 'Attentive carplet', null, 'Amblypharyngodon melettinus', 'OTHERS', 'OTHERS', 'Cyprinidae', 'Cypriniformes', 'LC', 0, 0, 0, 0, 0, 0, 1, 'TBD', 'TBD');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target,is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ('AG45', 0, 1, 0, 0, 1, 1,'Albacore, yellowfin tuna and bigeye tuna', 'Germon; Albacore; Patudo; Thon obèse', 'TUNAS', 'OTHERS');
INSERT INTO refs_biological.species ( code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ('AG39', 0, 1, 0, 0, 1, 1,'Yellowfin tuna; bigeye tuna; albacore; swordfish; marlins nei', 'Albacore, listao, patudo, germon, espadon, makaires nca', 'TUNAS', 'OTHERS');
INSERT INTO refs_biological.species ( code, is_bait, is_iotc, is_predator, is_ssi, is_target,is_aggregate, name_en, name_fr, species_group_code,  species_category_code) VALUES ('AG03', 0, 1, 0, 0, 1, 1,'Marlins nei', 'Marlin rayé et makaires nca', 'BILLFISH', 'OTHERS');
INSERT INTO refs_biological.species ( code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG13', 0, 1, 0, 0, 1, 1,'Tunas nei', 'Thonidés nca', 'TUNAS', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG12', 0, 1, 0, 0, 1, 1,'Tuna-like fishes nei', 'Poissons type thon nca', 'TUNAS', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ('AG11', 0, 1, 0, 0, 1, 1,'True tunas nei', 'Thons Thunnus nca', 'TUNAS', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG40', 0, 1, 0, 0, 1, 1,'Albacore, frigate tuna and bullet tuna', 'Germon, Auxide et bonitou', 'TUNAS', 'OTHERS');
-- Added for ros_ll.ll_catch_details.species_code
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG04', 0, 1, 0, 0, 1,1, 'Marlins, sailfish, spearfish nei', 'Makaires et marlins et voiliers nca', 'BILLFISH', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG09', 0, 1, 0, 0, 1,1, 'Wahoo and seerfishes nei', 'Thazards nca', 'SEERFISH', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'RMJ', 0, 0, 1, 0, 1,1, 'Spinetail mobula', null, 'SHARKS',  'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG15', 0, 0, 1, 0, 1,1, 'Dogfishes nei', 'Aiguillats nca', 'SHARKS', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG16', 0, 0, 1, 0, 1,1, 'Hammerhead sharks nei', 'Requins marteau nca', 'SHARKS', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG17', 0, 0, 1, 0, 1,1, 'Mako sharks', 'Taupes', 'SHARKS', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG30', 0, 0, 1, 0, 1,1, 'Mantas, devil rays nei', 'Mantes, diables de mer nca', 'SHARKS', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG18', 0, 0, 1, 0, 1,1, 'Rays, stingrays, mantas nei', 'Raies et pastenagues et mantes nca', 'SHARKS', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG22', 0, 0, 1, 0, 1,1, 'Sharks various nei', 'Requins divers nca', 'SHARKS', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG23', 0, 0, 1, 1, 1,1, 'Thresher sharks nei', 'Renards de mer nca', 'SHARKS', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG00', 0, 0, 0, 0, 1,1, 'Unknown', 'Espèces non ciblées, associées et dépendantes', 'OTHERS',  'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG24', 0, 0, 0, 0, 1,1, 'Dolphinfishes, nei', 'Coryphènes nca', 'OTHERS',  'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG27', 0, 0, 0, 0, 1,1, 'Non-IOTC species', 'Poissons marins nca', 'OTHERS',  'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG32', 0, 0, 0, 0, 1,1, 'Barracudas', 'Brochets de mer', 'OTHERS',  'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG50', 0, 0, 0, 1, 0,1, 'Sea turtles nei', null, 'OTHERS', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG71', 0, 0, 1, 1, 1,1, 'Devil rays nei', null, 'SHARKS', 'OTHERS');
-- Added for ros_ll.ll_setting_operations_target_species.species_code
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ('AG14', 0, 1, 0, 0, 1, 1,'Billfish nei', 'Poissons epée nca', 'BILLFISH', 'OTHERS');
-- Added for ros_ps.ps_catch_details.species_code
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG05', 0, 1, 0, 0, 1, 1,'Frigate tuna and bullet tuna', 'Auxide et bonitou', 'TUNAS', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG26', 0, 0, 0, 0, 1, 1,'Mackerels Indian, nei', 'Maquereaux Indo-pacifique nca', 'OTHERS', 'OTHERS');
INSERT INTO refs_biological.species (code, is_bait, is_iotc, is_predator, is_ssi, is_target, is_aggregate, name_en, name_fr, species_group_code, species_category_code) VALUES ( 'AG70', 0, 0, 1, 1, 1, 1,'Giant oceanic manta ray and Alfred manta (reef manta ray)', null, 'SHARKS', 'OTHERS');