END TRANSACTION;
BEGIN TRANSACTION;
ALTER TABLE ros_ll.ll_catch_details ADD COLUMN  type_of_fate_code CHAR(2);
ALTER TABLE ros_gn.gn_catch_details ADD COLUMN  type_of_fate_code CHAR(2);
ALTER TABLE ros_ps.ps_catch_details ADD COLUMN  type_of_fate_code CHAR(2);
ALTER TABLE ros_pl.pl_catch_details ADD COLUMN  type_of_fate_code CHAR(2);
ALTER TABLE ros_common.measured_lengths ADD COLUMN  type_of_measurement_code CHAR(2);
ALTER TABLE ros_common.estimated_weights ADD COLUMN  type_of_measurement_code CHAR(2);
ALTER TABLE ros_common.vessel_attributes_fish_storage_type ADD COLUMN fish_storage_type_code CHAR(2);
UPDATE ros_common.vessel_attributes_fish_storage_type SET fish_storage_type_code = (SELECT code FROM ROS_references.CL_FISH_STORAGE_TYPES cl WHERE cl.id = fish_storage_type_id);
ALTER TABLE ros_common.vessel_attributes_fish_storage_type ALTER COLUMN fish_storage_type_code SET NOT NULL;
ALTER TABLE ONLY ros_common.vessel_attributes_fish_storage_type ADD CONSTRAINT fk_ros_common_fish_storage_type_code_vessel_attributes_fish_storage_type FOREIGN KEY (fish_storage_type_code) REFERENCES refs_fishery.FISH_STORAGE_TYPES(code);
ALTER TABLE ros_gn.gillnet_configuration ADD COLUMN float_type_code CHAR(2);
UPDATE ros_gn.gillnet_configuration SET float_type_code = (SELECT code FROM refs_fishery.FLOAT_TYPES WHERE code_orig = (SELECT code FROM ROS_references.CL_FLOAT_TYPES cl WHERE cl.id = float_type_id));
ALTER TABLE ONLY ros_gn.gillnet_configuration ADD CONSTRAINT fk_ros_gn_float_type_code_gillnet_configuration FOREIGN KEY (float_type_code) REFERENCES refs_fishery.FLOAT_TYPES(code);
ALTER TABLE ros_common.vessel_identification ADD COLUMN main_fishing_gear_code VARCHAR(16);
UPDATE ros_common.vessel_identification SET main_fishing_gear_code = (SELECT code FROM refs_fishery_config.GEARS WHERE code_orig = (SELECT code FROM Ros_references.CL_GEAR_TYPES cl WHERE cl.id = main_fishing_gear_id));
ALTER TABLE ONLY ros_common.vessel_identification ADD CONSTRAINT fk_ros_common_main_fishing_gear_code_vessel_identification FOREIGN KEY (main_fishing_gear_code) REFERENCES refs_fishery_config.GEARS(code);
ALTER TABLE ros_gn.gillnet_configuration ADD COLUMN gillnet_material_type_code CHAR(2);
UPDATE ros_gn.gillnet_configuration SET gillnet_material_type_code = (SELECT code FROM refs_fishery.GILLNET_MATERIAL_TYPES WHERE code_orig = (SELECT code FROM Ros_references.CL_GILLNET_MATERIAL_TYPES cl WHERE cl.id = gillnet_material_type_id));
ALTER TABLE ONLY ros_gn.gillnet_configuration ADD CONSTRAINT fk_ros_gn_gillnet_material_type_code_gillnet_configuration FOREIGN KEY (gillnet_material_type_code) REFERENCES refs_fishery.GILLNET_MATERIAL_TYPES(code);
ALTER TABLE ros_references.cl_ports ADD COLUMN country_code CHAR(3);
UPDATE ros_references.cl_ports SET country_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = country_id);
ALTER TABLE ONLY ros_references.cl_ports ADD CONSTRAINT fk_ros_references_country_code_cl_ports FOREIGN KEY (country_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_meta.ros_observers_2_flags ADD COLUMN flag_code CHAR(3);
UPDATE ros_meta.ros_observers_2_flags SET flag_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = flag_id);
ALTER TABLE ros_meta.ros_observers_2_flags ALTER COLUMN flag_code SET NOT NULL;
ALTER TABLE ONLY ros_meta.ros_observers_2_flags ADD CONSTRAINT fk_ros_meta_flag_code_ros_observers_2_flags FOREIGN KEY (flag_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_meta.ros_observers ADD COLUMN nationality_code CHAR(3);
UPDATE ros_meta.ros_observers SET nationality_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = nationality_id);
ALTER TABLE ros_meta.ros_observers ALTER COLUMN nationality_code SET NOT NULL;
ALTER TABLE ONLY ros_meta.ros_observers ADD CONSTRAINT fk_ros_meta_nationality_code_ros_observers FOREIGN KEY (nationality_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_common.activity_details ADD COLUMN activity_code CHAR(2);
UPDATE ros_common.activity_details SET activity_code = (SELECT code FROM refs_biological.BAIT_CONDITIONS WHERE code_orig = (SELECT code FROM ROS_references.CL_ACTIVITIES cl WHERE cl.id = activity_id));
ALTER TABLE ONLY ros_common.activity_details ADD CONSTRAINT fk_ros_common_activity_code_activity_details FOREIGN KEY (activity_code) REFERENCES refs_biological.BAIT_CONDITIONS(code);
ALTER TABLE ros_pl.baits_and_conditions ADD COLUMN bait_condition_code CHAR(2);
UPDATE ros_pl.baits_and_conditions SET bait_condition_code = (SELECT code FROM refs_biological.BAIT_CONDITIONS WHERE code_orig = (SELECT code FROM ROS_references.CL_BAIT_CONDITIONS cl WHERE cl.id = bait_condition_id));
ALTER TABLE ONLY ros_pl.baits_and_conditions ADD CONSTRAINT fk_ros_pl_bait_condition_code_baits_and_conditions FOREIGN KEY (bait_condition_code) REFERENCES refs_biological.BAIT_CONDITIONS(code);
ALTER TABLE ros_ll.baits_by_conditions ADD COLUMN bait_condition_code CHAR(2);
UPDATE ros_ll.baits_by_conditions SET bait_condition_code = (SELECT code FROM refs_biological.BAIT_CONDITIONS WHERE code_orig = (SELECT code FROM ROS_references.CL_BAIT_CONDITIONS cl WHERE cl.id = bait_condition_id));
ALTER TABLE ONLY ros_ll.baits_by_conditions ADD CONSTRAINT fk_ros_ll_bait_condition_code_baits_by_conditions FOREIGN KEY (bait_condition_code) REFERENCES refs_biological.BAIT_CONDITIONS(code);
ALTER TABLE ros_ll.ll_additional_catch_details_on_ssi ADD COLUMN bait_condition_code CHAR(2);
UPDATE ros_ll.ll_additional_catch_details_on_ssi SET bait_condition_code = (SELECT code FROM refs_biological.BAIT_CONDITIONS WHERE code_orig = (SELECT code FROM ROS_references.CL_BAIT_CONDITIONS cl WHERE cl.id = bait_condition_id));
ALTER TABLE ONLY ros_ll.ll_additional_catch_details_on_ssi ADD CONSTRAINT fk_ros_ll_bait_condition_code_ll_additional_catch_details_on_ssi FOREIGN KEY (bait_condition_code) REFERENCES refs_biological.BAIT_CONDITIONS(code);
ALTER TABLE ros_pl.bait_fishing_operations ADD COLUMN bait_fishing_method_code CHAR(2);
UPDATE ros_pl.bait_fishing_operations SET bait_fishing_method_code = (SELECT code FROM refs_fishery.BAIT_FISHING_METHODS WHERE code_orig = (SELECT code FROM ROS_references.CL_BAIT_FISHING_METHODS cl WHERE cl.id = bait_fishing_method_id));
ALTER TABLE ONLY ros_pl.bait_fishing_operations ADD CONSTRAINT fk_ros_pl_bait_fishing_method_code_bait_fishing_operations FOREIGN KEY (bait_fishing_method_code) REFERENCES refs_fishery.BAIT_FISHING_METHODS(code);
ALTER TABLE ros_pl.bait_fishing_operations ADD COLUMN bait_school_detection_method_code CHAR(2);
UPDATE ros_pl.bait_fishing_operations SET bait_school_detection_method_code = (SELECT code FROM refs_fishery.BAIT_SCHOOL_DETECTION_METHODS WHERE code_orig = (SELECT code FROM ROS_references.CL_BAIT_SCHOOL_DETECTION_METHODS cl WHERE cl.id = bait_school_detection_method_id));
ALTER TABLE ONLY ros_pl.bait_fishing_operations ADD CONSTRAINT fk_ros_pl_bait_school_detection_method_code_bait_fishing_operations FOREIGN KEY (bait_school_detection_method_code) REFERENCES refs_fishery.BAIT_SCHOOL_DETECTION_METHODS(code);
ALTER TABLE ros_common.biometric_information ADD COLUMN bio_collection_sampling_method_code CHAR(2);
UPDATE ros_common.biometric_information SET bio_collection_sampling_method_code = (SELECT code FROM refs_biological.SAMPLING_METHODS_FOR_SAMPLING_COLLECTIONS WHERE code_orig = (SELECT code FROM ROS_references.CL_BIO_COLLECTION_SAMPLING_METHODS cl WHERE cl.id = bio_collection_sampling_method_id));
ALTER TABLE ONLY ros_common.biometric_information ADD CONSTRAINT fk_ros_common_bio_collection_sampling_method_code_biometric_information FOREIGN KEY (bio_collection_sampling_method_code) REFERENCES refs_biological.SAMPLING_METHODS_FOR_SAMPLING_COLLECTIONS(code);
ALTER TABLE ros_gn.gn_catch_details ADD COLUMN estimated_weight_sampling_method_code CHAR(2);
UPDATE ros_gn.gn_catch_details SET estimated_weight_sampling_method_code = (SELECT code FROM refs_biological.SAMPLING_METHODS_FOR_CATCH_ESTIMATION WHERE code_orig = (SELECT code FROM Ros_references.CL_CATCH_ESTIMATES_SAMPLING_METHODS cl WHERE cl.id = estimated_weight_sampling_method_id));
ALTER TABLE ONLY ros_gn.gn_catch_details ADD CONSTRAINT fk_ros_gn_estimated_weight_sampling_method_code_gn_catch_details FOREIGN KEY (estimated_weight_sampling_method_code) REFERENCES refs_biological.SAMPLING_METHODS_FOR_CATCH_ESTIMATION(code);
ALTER TABLE ros_ll.ll_catch_details ADD COLUMN estimated_weight_sampling_method_code CHAR(2);
UPDATE ros_ll.ll_catch_details SET estimated_weight_sampling_method_code = (SELECT code FROM refs_biological.SAMPLING_METHODS_FOR_CATCH_ESTIMATION WHERE code_orig = (SELECT code FROM Ros_references.CL_CATCH_ESTIMATES_SAMPLING_METHODS cl WHERE cl.id = estimated_weight_sampling_method_id));
ALTER TABLE ONLY ros_ll.ll_catch_details ADD CONSTRAINT fk_ros_ll_estimated_weight_sampling_method_code_ll_catch_details FOREIGN KEY (estimated_weight_sampling_method_code) REFERENCES refs_biological.SAMPLING_METHODS_FOR_CATCH_ESTIMATION(code);
ALTER TABLE ros_pl.pl_catch_details ADD COLUMN estimated_weight_sampling_method_code CHAR(2);
UPDATE ros_pl.pl_catch_details SET estimated_weight_sampling_method_code = (SELECT code FROM refs_biological.SAMPLING_METHODS_FOR_CATCH_ESTIMATION WHERE code_orig = (SELECT code FROM Ros_references.CL_CATCH_ESTIMATES_SAMPLING_METHODS cl WHERE cl.id = estimated_weight_sampling_method_id));
ALTER TABLE ONLY ros_pl.pl_catch_details ADD CONSTRAINT fk_ros_pl_estimated_weight_sampling_method_code_pl_catch_details FOREIGN KEY (estimated_weight_sampling_method_code) REFERENCES refs_biological.SAMPLING_METHODS_FOR_CATCH_ESTIMATION(code);
ALTER TABLE ros_ps.ps_catch_details ADD COLUMN estimated_weight_sampling_method_code CHAR(2);
UPDATE ros_ps.ps_catch_details SET estimated_weight_sampling_method_code = (SELECT code FROM refs_biological.SAMPLING_METHODS_FOR_CATCH_ESTIMATION WHERE code_orig = (SELECT code FROM Ros_references.CL_CATCH_ESTIMATES_SAMPLING_METHODS cl WHERE cl.id = estimated_weight_sampling_method_id));
ALTER TABLE ONLY ros_ps.ps_catch_details ADD CONSTRAINT fk_ros_ps_estimated_weight_sampling_method_code_ps_catch_details FOREIGN KEY (estimated_weight_sampling_method_code) REFERENCES refs_biological.SAMPLING_METHODS_FOR_CATCH_ESTIMATION(code);
ALTER TABLE ros_common.carrier_vessel_identification ADD COLUMN vessel_flag_code CHAR(3);
UPDATE ros_common.carrier_vessel_identification SET vessel_flag_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = vessel_flag_id);
ALTER TABLE ONLY ros_common.carrier_vessel_identification ADD CONSTRAINT fk_ros_common_vessel_flag_code_carrier_vessel_identification FOREIGN KEY (vessel_flag_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_common.iotc_person_contact_details ADD COLUMN nationality_code CHAR(3);
UPDATE ros_common.iotc_person_contact_details SET nationality_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = nationality_id);
ALTER TABLE ONLY ros_common.iotc_person_contact_details ADD CONSTRAINT fk_ros_common_nationality_code_iotc_person_contact_details FOREIGN KEY (nationality_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_common.iotc_person_details ADD COLUMN nationality_code CHAR(3);
UPDATE ros_common.iotc_person_details SET nationality_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = nationality_id);
ALTER TABLE ONLY ros_common.iotc_person_details ADD CONSTRAINT fk_ros_common_nationality_code_iotc_person_details FOREIGN KEY (nationality_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_common.locations ADD COLUMN country_code CHAR(3);
UPDATE ros_common.locations SET country_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = country_id);
ALTER TABLE ONLY ros_common.locations ADD CONSTRAINT fk_ros_common_country_code_locations FOREIGN KEY (country_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_common.observer_identification ADD COLUMN nationality_code CHAR(3);
UPDATE ros_common.observer_identification SET nationality_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = nationality_id);
ALTER TABLE ONLY ros_common.observer_identification ADD CONSTRAINT fk_ros_common_nationality_code_observer_identification FOREIGN KEY (nationality_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_common.person_contact_details ADD COLUMN nationality_code CHAR(3);
UPDATE ros_common.person_contact_details SET nationality_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = nationality_id);
ALTER TABLE ONLY ros_common.person_contact_details ADD CONSTRAINT fk_ros_common_nationality_code_person_contact_details FOREIGN KEY (nationality_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_common.person_details ADD COLUMN nationality_code CHAR(3);
UPDATE ros_common.person_details SET nationality_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = nationality_id);
ALTER TABLE ONLY ros_common.person_details ADD CONSTRAINT fk_ros_common_nationality_code_person_details FOREIGN KEY (nationality_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_common.vessel_identification ADD COLUMN flag_code CHAR(3);
UPDATE ros_common.vessel_identification SET flag_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = flag_id);
ALTER TABLE ONLY ros_common.vessel_identification ADD CONSTRAINT fk_ros_common_flag_code_vessel_identification FOREIGN KEY (flag_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_gn.gn_observer_data ADD COLUMN reporting_country_code CHAR(3);
UPDATE ros_gn.gn_observer_data SET reporting_country_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = reporting_country_id);
ALTER TABLE ros_gn.gn_observer_data ALTER COLUMN reporting_country_code SET NOT NULL;
ALTER TABLE ONLY ros_gn.gn_observer_data ADD CONSTRAINT fk_ros_gn_reporting_country_code_gn_observer_data FOREIGN KEY (reporting_country_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_ll.ll_observer_data ADD COLUMN reporting_country_code CHAR(3);
UPDATE ros_ll.ll_observer_data SET reporting_country_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = reporting_country_id);
ALTER TABLE ros_ll.ll_observer_data ALTER COLUMN reporting_country_code SET NOT NULL;
ALTER TABLE ONLY ros_ll.ll_observer_data ADD CONSTRAINT fk_ros_ll_reporting_country_code_ll_observer_data FOREIGN KEY (reporting_country_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_pl.pl_observer_data ADD COLUMN reporting_country_code CHAR(3);
UPDATE ros_pl.pl_observer_data SET reporting_country_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = reporting_country_id);
ALTER TABLE ros_pl.pl_observer_data ALTER COLUMN reporting_country_code SET NOT NULL;
ALTER TABLE ONLY ros_pl.pl_observer_data ADD CONSTRAINT fk_ros_pl_reporting_country_code_pl_observer_data FOREIGN KEY (reporting_country_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_ps.ps_observer_data ADD COLUMN reporting_country_code CHAR(3);
UPDATE ros_ps.ps_observer_data SET reporting_country_code = (SELECT code FROM ROS_references.CL_COUNTRIES cl WHERE cl.id = reporting_country_id);
ALTER TABLE ros_ps.ps_observer_data ALTER COLUMN reporting_country_code SET NOT NULL;
ALTER TABLE ONLY ros_ps.ps_observer_data ADD CONSTRAINT fk_ros_ps_reporting_country_code_ps_observer_data FOREIGN KEY (reporting_country_code) REFERENCES refs_admin.COUNTRIES(code);
ALTER TABLE ros_ll.ll_additional_catch_details_on_ssi ADD COLUMN dehooker_device_code CHAR(2);
UPDATE ros_ll.ll_additional_catch_details_on_ssi SET dehooker_device_code = (SELECT code FROM ROS_references.CL_DEHOOKER_DEVICES cl WHERE cl.id = dehooker_device_id);
ALTER TABLE ONLY ros_ll.ll_additional_catch_details_on_ssi ADD CONSTRAINT fk_ros_ll_dehooker_device_code_ll_additional_catch_details_on_ssi FOREIGN KEY (dehooker_device_code) REFERENCES refs_fishery.DEHOOKER_TYPES(code);
ALTER TABLE ros_common.waste_managements ADD COLUMN waste_storage_or_disposal_method_code CHAR(2);
UPDATE ros_common.waste_managements SET waste_storage_or_disposal_method_code = (SELECT code FROM ROS_references.CL_DISPOSAL_METHODS cl WHERE cl.id = waste_storage_or_disposal_method_id);
ALTER TABLE ONLY ros_common.waste_managements ADD CONSTRAINT fk_ros_common_waste_storage_or_disposal_method_code_waste_managements FOREIGN KEY (waste_storage_or_disposal_method_code) REFERENCES refs_fishery.WASTE_DISPOSAL_METHODS(code);
ALTER TABLE ros_ps.ps_object_details ADD COLUMN fad_raft_design_code CHAR(2);
UPDATE ros_ps.ps_object_details SET fad_raft_design_code = (SELECT code FROM refs_fishery.FAD_RAFT_DESIGNS WHERE code_orig = (SELECT code FROM ROS_references.CL_FAD_RAFT_DESIGNS cl WHERE cl.id = fad_raft_design_id));
ALTER TABLE ONLY ros_ps.ps_object_details ADD CONSTRAINT fk_ros_ps_fad_raft_design_code_ps_object_details FOREIGN KEY (fad_raft_design_code) REFERENCES refs_fishery.FAD_RAFT_DESIGNS(code);
ALTER TABLE ros_ps.ps_object_details ADD COLUMN fad_tail_design_code CHAR(2);
UPDATE ros_ps.ps_object_details SET fad_tail_design_code = (SELECT code FROM refs_fishery.FAD_TAIL_DESIGNS WHERE code_orig = (SELECT code FROM ROS_references.CL_FAD_TAIL_DESIGNS cl WHERE cl.id = fad_tail_design_id));
ALTER TABLE ONLY ros_ps.ps_object_details ADD CONSTRAINT fk_ros_ps_fad_tail_design_code_ps_object_details FOREIGN KEY (fad_tail_design_code) REFERENCES refs_fishery.FAD_TAIL_DESIGNS(code);
ALTER TABLE ros_ll.ll_catch_details ADD COLUMN fates_code CHAR(2);
UPDATE ros_ll.ll_catch_details SET fates_code = (SELECT code FROM refs_biological.FATES WHERE code_orig = (SELECT code FROM Ros_references.CL_FATES cl WHERE cl.id = fates_id));
UPDATE ros_ll.ll_catch_details SET type_of_fate_code = (SELECT type_of_fate_code FROM refs_biological.FATES WHERE code_orig = (SELECT code FROM Ros_references.CL_FATES cl WHERE cl.id = fates_id));
ALTER TABLE ONLY ros_ll.ll_catch_details ADD CONSTRAINT fk_ros_ll_fates_code_ll_catch_details FOREIGN KEY (fates_code, type_of_fate_code) REFERENCES refs_biological.FATES(code, type_of_fate_code);
ALTER TABLE ros_gn.gn_catch_details ADD COLUMN fates_code CHAR(2);
UPDATE ros_gn.gn_catch_details SET fates_code = (SELECT code FROM refs_biological.FATES WHERE code_orig = (SELECT code FROM Ros_references.CL_FATES cl WHERE cl.id = fates_id));
UPDATE ros_gn.gn_catch_details SET type_of_fate_code = (SELECT type_of_fate_code FROM refs_biological.FATES WHERE code_orig = (SELECT code FROM Ros_references.CL_FATES cl WHERE cl.id = fates_id));
ALTER TABLE ONLY ros_gn.gn_catch_details ADD CONSTRAINT fk_ros_gn_fates_code_gn_catch_details FOREIGN KEY (fates_code, type_of_fate_code) REFERENCES refs_biological.FATES(code, type_of_fate_code);
ALTER TABLE ros_pl.pl_catch_details ADD COLUMN fates_code CHAR(2);
UPDATE ros_pl.pl_catch_details SET fates_code = (SELECT code FROM refs_biological.FATES WHERE code_orig = (SELECT code FROM Ros_references.CL_FATES cl WHERE cl.id = fates_id));
UPDATE ros_pl.pl_catch_details SET type_of_fate_code = (SELECT type_of_fate_code FROM refs_biological.FATES WHERE code_orig = (SELECT code FROM Ros_references.CL_FATES cl WHERE cl.id = fates_id));
ALTER TABLE ONLY ros_pl.pl_catch_details ADD CONSTRAINT fk_ros_pl_fates_code_pl_catch_details FOREIGN KEY (fates_code, type_of_fate_code) REFERENCES refs_biological.FATES(code, type_of_fate_code);
ALTER TABLE ros_ps.ps_catch_details ADD COLUMN fates_code CHAR(2);
UPDATE ros_ps.ps_catch_details SET fates_code = (SELECT code FROM refs_biological.FATES WHERE code_orig = (SELECT code FROM Ros_references.CL_FATES cl WHERE cl.id = fates_id));
UPDATE ros_ps.ps_catch_details SET type_of_fate_code = (SELECT type_of_fate_code FROM refs_biological.FATES WHERE code_orig = (SELECT code FROM Ros_references.CL_FATES cl WHERE cl.id = fates_id));
ALTER TABLE ONLY ros_ps.ps_catch_details ADD CONSTRAINT fk_ros_ps_fates_code_ps_catch_details FOREIGN KEY (fates_code, type_of_fate_code) REFERENCES refs_biological.FATES(code, type_of_fate_code);
ALTER TABLE ros_common.vessel_attributes_fish_preservation_method ADD COLUMN fish_preservation_method_code CHAR(2);
UPDATE ros_common.vessel_attributes_fish_preservation_method SET fish_preservation_method_code = (SELECT code FROM refs_fishery.FISH_PRESERVATION_METHODS WHERE code_orig = (SELECT code FROM ROS_references.CL_FISH_PRESERVATION_METHODS cl WHERE cl.id = fish_preservation_method_id));
ALTER TABLE ros_common.vessel_attributes_fish_preservation_method ALTER COLUMN fish_preservation_method_code SET NOT NULL;
ALTER TABLE ONLY ros_common.vessel_attributes_fish_preservation_method ADD CONSTRAINT fk_ros_common_fish_preservation_method_code_vessel_attributes_fish_preservation_method FOREIGN KEY (fish_preservation_method_code) REFERENCES refs_fishery.FISH_PRESERVATION_METHODS(code);
ALTER TABLE ros_gn.gn_additional_catch_details_on_ssi ADD COLUMN gear_interaction_code CHAR(2);
UPDATE ros_gn.gn_additional_catch_details_on_ssi SET gear_interaction_code = (SELECT code FROM ROS_references.CL_GEAR_INTERACTIONS cl WHERE cl.id = gear_interaction_id);
ALTER TABLE ONLY ros_gn.gn_additional_catch_details_on_ssi ADD CONSTRAINT fk_ros_gn_gear_interaction_code_gn_additional_catch_details_on_ssi FOREIGN KEY (gear_interaction_code) REFERENCES refs_biological.GEAR_INTERACTIONS(code);
ALTER TABLE ros_ll.ll_additional_catch_details_on_ssi ADD COLUMN gear_interaction_code CHAR(2);
UPDATE ros_ll.ll_additional_catch_details_on_ssi SET gear_interaction_code = (SELECT code FROM ROS_references.CL_GEAR_INTERACTIONS cl WHERE cl.id = gear_interaction_id);
ALTER TABLE ONLY ros_ll.ll_additional_catch_details_on_ssi ADD CONSTRAINT fk_ros_ll_gear_interaction_code_ll_additional_catch_details_on_ssi FOREIGN KEY (gear_interaction_code) REFERENCES refs_biological.GEAR_INTERACTIONS(code);
ALTER TABLE ros_pl.pl_additional_catch_details_on_ssi ADD COLUMN gear_interaction_code CHAR(2);
UPDATE ros_pl.pl_additional_catch_details_on_ssi SET gear_interaction_code = (SELECT code FROM ROS_references.CL_GEAR_INTERACTIONS cl WHERE cl.id = gear_interaction_id);
ALTER TABLE ONLY ros_pl.pl_additional_catch_details_on_ssi ADD CONSTRAINT fk_ros_pl_gear_interaction_code_pl_additional_catch_details_on_ssi FOREIGN KEY (gear_interaction_code) REFERENCES refs_biological.GEAR_INTERACTIONS(code);
ALTER TABLE ros_ps.ps_additional_catch_details_on_ssi ADD COLUMN gear_interaction_code CHAR(2);
UPDATE ros_ps.ps_additional_catch_details_on_ssi SET gear_interaction_code = (SELECT code FROM ROS_references.CL_GEAR_INTERACTIONS cl WHERE cl.id = gear_interaction_id);
ALTER TABLE ONLY ros_ps.ps_additional_catch_details_on_ssi ADD CONSTRAINT fk_ros_ps_gear_interaction_code_ps_additional_catch_details_on_ssi FOREIGN KEY (gear_interaction_code) REFERENCES refs_biological.GEAR_INTERACTIONS(code);
ALTER TABLE ros_gn.gn_additional_catch_details_on_ssi ADD COLUMN handling_method_code CHAR(2);
UPDATE ros_gn.gn_additional_catch_details_on_ssi SET handling_method_code = (SELECT code FROM refs_biological.HANDLING_METHODS WHERE code_orig = (SELECT code FROM ROS_references.CL_HANDLING_METHODS cl WHERE cl.id = handling_method_id));
ALTER TABLE ONLY ros_gn.gn_additional_catch_details_on_ssi ADD CONSTRAINT fk_ros_gn_handling_method_code_gn_additional_catch_details_on_ssi FOREIGN KEY (handling_method_code) REFERENCES refs_biological.HANDLING_METHODS(code);
ALTER TABLE ros_ll.ll_additional_catch_details_on_ssi ADD COLUMN handling_method_code CHAR(2);
UPDATE ros_ll.ll_additional_catch_details_on_ssi SET handling_method_code = (SELECT code FROM refs_biological.HANDLING_METHODS WHERE code_orig = (SELECT code FROM ROS_references.CL_HANDLING_METHODS cl WHERE cl.id = handling_method_id));
ALTER TABLE ONLY ros_ll.ll_additional_catch_details_on_ssi ADD CONSTRAINT fk_ros_ll_handling_method_code_ll_additional_catch_details_on_ssi FOREIGN KEY (handling_method_code) REFERENCES refs_biological.HANDLING_METHODS(code);
ALTER TABLE ros_pl.pl_additional_catch_details_on_ssi ADD COLUMN handling_method_code CHAR(2);
UPDATE ros_pl.pl_additional_catch_details_on_ssi SET handling_method_code = (SELECT code FROM refs_biological.HANDLING_METHODS WHERE code_orig = (SELECT code FROM ROS_references.CL_HANDLING_METHODS cl WHERE cl.id = handling_method_id));
ALTER TABLE ONLY ros_pl.pl_additional_catch_details_on_ssi ADD CONSTRAINT fk_ros_pl_handling_method_code_pl_additional_catch_details_on_ssi FOREIGN KEY (handling_method_code) REFERENCES refs_biological.HANDLING_METHODS(code);
ALTER TABLE ros_ps.ps_additional_catch_details_on_ssi ADD COLUMN handling_method_code CHAR(2);
UPDATE ros_ps.ps_additional_catch_details_on_ssi SET handling_method_code = (SELECT code FROM refs_biological.HANDLING_METHODS WHERE code_orig = (SELECT code FROM ROS_references.CL_HANDLING_METHODS cl WHERE cl.id = handling_method_id));
ALTER TABLE ONLY ros_ps.ps_additional_catch_details_on_ssi ADD CONSTRAINT fk_ros_ps_handling_method_code_ps_additional_catch_details_on_ssi FOREIGN KEY (handling_method_code) REFERENCES refs_biological.HANDLING_METHODS(code);
ALTER TABLE ros_ll.hooks_by_type ADD COLUMN hook_type_code CHAR(3);
UPDATE ros_ll.hooks_by_type SET hook_type_code = (SELECT code FROM ROS_references.CL_HOOKS cl WHERE cl.id = hook_type_id);
ALTER TABLE ONLY ros_ll.hooks_by_type ADD CONSTRAINT fk_ros_ll_hook_type_code_hooks_by_type FOREIGN KEY (hook_type_code) REFERENCES refs_fishery.HOOK_TYPES(code);
ALTER TABLE ros_pl.lures_or_jiggers_by_type ADD COLUMN hook_type_code CHAR(3);
UPDATE ros_pl.lures_or_jiggers_by_type SET hook_type_code = (SELECT code FROM ROS_references.CL_HOOKS cl WHERE cl.id = hook_type_id);
ALTER TABLE ONLY ros_pl.lures_or_jiggers_by_type ADD CONSTRAINT fk_ros_pl_hook_type_code_lures_or_jiggers_by_type FOREIGN KEY (hook_type_code) REFERENCES refs_fishery.HOOK_TYPES(code);
ALTER TABLE ros_pl.pl_general_gear_attributes ADD COLUMN hook_type_code CHAR(3);
UPDATE ros_pl.pl_general_gear_attributes SET hook_type_code = (SELECT code FROM Ros_references.CL_HOOKS cl WHERE cl.id = hook_type_id);
ALTER TABLE ONLY ros_pl.pl_general_gear_attributes ADD CONSTRAINT fk_ros_pl_hook_type_code_pl_general_gear_attributes FOREIGN KEY (hook_type_code) REFERENCES refs_fishery.HOOK_TYPES(code);
ALTER TABLE ros_common.vessel_attributes ADD COLUMN hull_material_code CHAR(2);
UPDATE ros_common.vessel_attributes SET hull_material_code = (SELECT code FROM refs_fishery.HULL_MATERIAL_TYPES WHERE code_orig = (SELECT code FROM Ros_references.CL_HULL_MATERIALS cl WHERE cl.id = hull_material_id));
ALTER TABLE ONLY ros_common.vessel_attributes ADD CONSTRAINT fk_ros_common_hull_material_code_vessel_attributes FOREIGN KEY (hull_material_code) REFERENCES refs_fishery.HULL_MATERIAL_TYPES(code);
ALTER TABLE ros_common.additional_details_on_non_target_species ADD COLUMN condition_at_capture_code VARCHAR(3);
UPDATE ros_common.additional_details_on_non_target_species SET condition_at_capture_code = (SELECT code FROM ROS_references.CL_INCIDENTAL_CAPTURES_CONDITIONS cl WHERE cl.id = condition_at_capture_id);
ALTER TABLE ONLY ros_common.additional_details_on_non_target_species ADD CONSTRAINT fk_ros_common_condition_at_capture_code_additional_details_on_non_target_species FOREIGN KEY (condition_at_capture_code) REFERENCES refs_biological.INCIDENTAL_CAPTURES_CONDITIONS(code);
ALTER TABLE ros_common.additional_details_on_non_target_species ADD COLUMN condition_at_release_code VARCHAR(3);
UPDATE ros_common.additional_details_on_non_target_species SET condition_at_release_code = (SELECT code FROM ROS_references.CL_INCIDENTAL_CAPTURES_CONDITIONS cl WHERE cl.id = condition_at_release_id);
ALTER TABLE ONLY ros_common.additional_details_on_non_target_species ADD CONSTRAINT fk_ros_common_condition_at_release_code_additional_details_on_non_target_species FOREIGN KEY (condition_at_release_code) REFERENCES refs_biological.INCIDENTAL_CAPTURES_CONDITIONS(code);
ALTER TABLE ros_common.measured_lengths ADD COLUMN measured_length_type_code CHAR(2);
UPDATE ros_common.measured_lengths SET measured_length_type_code = (SELECT code FROM refs_biological.MEASUREMENTS WHERE measured_lengths.measured_length_type_code ='LN' AND code_orig = (SELECT code FROM Ros_references.CL_LENGTH_MEASUREMENT_TYPES cl WHERE cl.id = measured_length_type_id));
UPDATE ros_common.measured_lengths SET type_of_measurement_code = 'LN';
ALTER TABLE ONLY ros_common.measured_lengths ADD CONSTRAINT fk_ros_common_measured_length_type_code_measured_lengths FOREIGN KEY (measured_length_type_code, type_of_measurement_code) REFERENCES refs_biological.MEASUREMENTS(code, type_of_measurement_code);
ALTER TABLE ros_common.measured_lengths ADD COLUMN length_measuring_tool_code CHAR(2);
UPDATE ros_common.measured_lengths SET length_measuring_tool_code = (SELECT code FROM ROS_references.CL_LENGTH_MEASURING_TOOLS cl WHERE cl.id = length_measuring_tool_id);
ALTER TABLE ONLY ros_common.measured_lengths ADD CONSTRAINT fk_ros_common_length_measuring_tool_code_measured_lengths FOREIGN KEY (length_measuring_tool_code, type_of_measurement_code) REFERENCES refs_biological.MEASUREMENT_TOOLS(code, type_of_measurement_code);
ALTER TABLE ros_ll.lights_by_type_and_colour ADD COLUMN light_colour_code CHAR(2);
UPDATE ros_ll.lights_by_type_and_colour SET light_colour_code = (SELECT code FROM ROS_references.CL_LIGHT_COLOURS cl WHERE cl.id = light_colour_id);
ALTER TABLE ONLY ros_ll.lights_by_type_and_colour ADD CONSTRAINT fk_ros_ll_light_colour_code_lights_by_type_and_colour FOREIGN KEY (light_colour_code) REFERENCES refs_fishery.LIGHT_COLOURS(code);
ALTER TABLE ros_ll.lights_by_type_and_colour ADD COLUMN light_type_code CHAR(2);
UPDATE ros_ll.lights_by_type_and_colour SET light_type_code = (SELECT code FROM ROS_references.CL_LIGHT_TYPES cl WHERE cl.id = light_type_id);
ALTER TABLE ONLY ros_ll.lights_by_type_and_colour ADD CONSTRAINT fk_ros_ll_light_type_code_lights_by_type_and_colour FOREIGN KEY (light_type_code) REFERENCES refs_fishery.LIGHT_TYPES(code);
ALTER TABLE ros_ll.branchline_sections ADD COLUMN branchline_material_type_code CHAR(2);
UPDATE ros_ll.branchline_sections SET branchline_material_type_code = (SELECT code FROM refs_fishery.LINE_MATERIAL_TYPES WHERE code_orig = (SELECT code FROM ROS_references.CL_LINE_MATERIAL_TYPES cl WHERE cl.id = branchline_material_type_id));
ALTER TABLE ONLY ros_ll.branchline_sections ADD CONSTRAINT fk_ros_ll_branchline_material_type_code_branchline_sections FOREIGN KEY (branchline_material_type_code) REFERENCES refs_fishery.LINE_MATERIAL_TYPES(code);
ALTER TABLE ros_ll.ll_additional_catch_details_on_ssi ADD COLUMN leader_material_type_code CHAR(2);
UPDATE ros_ll.ll_additional_catch_details_on_ssi SET leader_material_type_code = (SELECT code FROM refs_fishery.LINE_MATERIAL_TYPES WHERE code_orig = (SELECT code FROM ROS_references.CL_LINE_MATERIAL_TYPES cl WHERE cl.id = leader_material_type_id));
ALTER TABLE ONLY ros_ll.ll_additional_catch_details_on_ssi ADD CONSTRAINT fk_ros_ll_leader_material_type_code_ll_additional_catch_details_on_ssi FOREIGN KEY (leader_material_type_code) REFERENCES refs_fishery.LINE_MATERIAL_TYPES(code);
ALTER TABLE ros_ll.ll_general_gear_attributes ADD COLUMN line_material_type_code CHAR(2);
UPDATE ros_ll.ll_general_gear_attributes SET line_material_type_code = (SELECT code FROM refs_fishery.LINE_MATERIAL_TYPES WHERE code_orig = (SELECT code FROM ROS_references.CL_LINE_MATERIAL_TYPES cl WHERE cl.id = line_material_type_id));
ALTER TABLE ONLY ros_ll.ll_general_gear_attributes ADD CONSTRAINT fk_ros_ll_line_material_type_code_ll_general_gear_attributes FOREIGN KEY (line_material_type_code) REFERENCES refs_fishery.LINE_MATERIAL_TYPES(code);
ALTER TABLE ros_gn.gn_mitigation_measures_mitigation_devices ADD COLUMN mitigation_device_code CHAR(2);
UPDATE ros_gn.gn_mitigation_measures_mitigation_devices SET mitigation_device_code = (SELECT code FROM refs_fishery.MITIGATION_DEVICES WHERE code_orig = (SELECT code FROM ROS_references.CL_MITIGATION_DEVICES cl WHERE cl.id = mitigation_device_id));
ALTER TABLE ros_gn.gn_mitigation_measures_mitigation_devices ALTER COLUMN mitigation_device_code SET NOT NULL;
ALTER TABLE ONLY ros_gn.gn_mitigation_measures_mitigation_devices ADD CONSTRAINT fk_ros_gn_mitigation_device_code_gn_mitigation_measures_mitigation_devices FOREIGN KEY (mitigation_device_code) REFERENCES refs_fishery.MITIGATION_DEVICES(code);
ALTER TABLE ros_ll.ll_gear_specifications_mitigation_device ADD COLUMN mitigation_device_code CHAR(2);
UPDATE ros_ll.ll_gear_specifications_mitigation_device SET mitigation_device_code = (SELECT code FROM refs_fishery.MITIGATION_DEVICES WHERE code_orig = (SELECT code FROM ROS_references.CL_MITIGATION_DEVICES cl WHERE cl.id = mitigation_device_id));
ALTER TABLE ros_ll.ll_gear_specifications_mitigation_device ALTER COLUMN mitigation_device_code SET NOT NULL;
ALTER TABLE ONLY ros_ll.ll_gear_specifications_mitigation_device ADD CONSTRAINT fk_ros_ll_mitigation_device_code_ll_gear_specifications_mitigation_device FOREIGN KEY (mitigation_device_code) REFERENCES refs_fishery.MITIGATION_DEVICES(code);
ALTER TABLE ros_ll.ll_mitigation_measures_mitigation_devices ADD COLUMN mitigation_device_code CHAR(2);
UPDATE ros_ll.ll_mitigation_measures_mitigation_devices SET mitigation_device_code = (SELECT code FROM refs_fishery.MITIGATION_DEVICES WHERE code_orig = (SELECT code FROM ROS_references.CL_MITIGATION_DEVICES cl WHERE cl.id = mitigation_device_id));
ALTER TABLE ros_ll.ll_mitigation_measures_mitigation_devices ALTER COLUMN mitigation_device_code SET NOT NULL;
ALTER TABLE ONLY ros_ll.ll_mitigation_measures_mitigation_devices ADD CONSTRAINT fk_ros_ll_mitigation_device_code_ll_mitigation_measures_mitigation_devices FOREIGN KEY (mitigation_device_code) REFERENCES refs_fishery.MITIGATION_DEVICES(code);
ALTER TABLE ros_gn.gn_gillnet_configuration_net_web_colours ADD COLUMN net_colour_code CHAR(2);
UPDATE ros_gn.gn_gillnet_configuration_net_web_colours SET net_colour_code = (SELECT code FROM refs_fishery.NET_COLOURS WHERE code_orig = (SELECT code FROM ROS_references.CL_NET_COLOURS cl WHERE cl.id = net_colour_id));
ALTER TABLE ros_gn.gn_gillnet_configuration_net_web_colours ALTER COLUMN net_colour_code SET NOT NULL;
ALTER TABLE ONLY ros_gn.gn_gillnet_configuration_net_web_colours ADD CONSTRAINT fk_ros_gn_net_colour_code_gn_gillnet_configuration_net_web_colours FOREIGN KEY (net_colour_code) REFERENCES refs_fishery.NET_COLOURS(code);
ALTER TABLE ros_gn.gn_hauling_operations ADD COLUMN net_condition_code CHAR(2);
UPDATE ros_gn.gn_hauling_operations SET net_condition_code = (SELECT code FROM refs_fishery.NET_CONDITIONS WHERE code_orig = (SELECT code FROM ROS_references.CL_NET_CONDITIONS cl WHERE cl.id = net_condition_id));
ALTER TABLE ONLY ros_gn.gn_hauling_operations ADD CONSTRAINT fk_ros_gn_net_condition_code_gn_hauling_operations FOREIGN KEY (net_condition_code) REFERENCES refs_fishery.NET_CONDITIONS(code);
ALTER TABLE ros_gn.gn_setting_operations ADD COLUMN net_configuration_code CHAR(2);
UPDATE ros_gn.gn_setting_operations SET net_configuration_code = (SELECT code FROM ROS_references.CL_NET_CONFIGURATIONS cl WHERE cl.id = net_configuration_id);
ALTER TABLE ONLY ros_gn.gn_setting_operations ADD CONSTRAINT fk_ros_gn_net_configuration_code_gn_setting_operations FOREIGN KEY (net_configuration_code) REFERENCES refs_fishery.NET_CONFIGURATIONS(code);
ALTER TABLE ros_gn.gn_setting_operations ADD COLUMN net_deploy_depth_code CHAR(2);
UPDATE ros_gn.gn_setting_operations SET net_deploy_depth_code = (SELECT code FROM refs_fishery.NET_DEPLOY_DEPTHS WHERE code_orig = (SELECT code FROM Ros_references.CL_NET_DEPLOY_DEPTHS cl WHERE cl.id = net_deploy_depth_id));
ALTER TABLE ONLY ros_gn.gn_setting_operations ADD CONSTRAINT fk_ros_gn_net_deploy_depth_code_gn_setting_operations FOREIGN KEY (net_deploy_depth_code) REFERENCES refs_fishery.NET_DEPLOY_DEPTHS(code);
ALTER TABLE ros_gn.gn_setting_operations ADD COLUMN net_setting_strategy_code CHAR(2);
UPDATE ros_gn.gn_setting_operations SET net_setting_strategy_code = (SELECT code FROM refs_fishery.NET_SETTING_STRATEGIES WHERE code_orig = (SELECT code FROM ROS_references.CL_NET_SETTING_STRATEGIES cl WHERE cl.id = net_setting_strategy_id));
ALTER TABLE ONLY ros_gn.gn_setting_operations ADD CONSTRAINT fk_ros_gn_net_setting_strategy_code_gn_setting_operations FOREIGN KEY (net_setting_strategy_code) REFERENCES refs_fishery.NET_SETTING_STRATEGIES(code);
ALTER TABLE ros_common.estimated_weights ADD COLUMN processing_type_code CHAR(2);
UPDATE ros_common.estimated_weights SET processing_type_code = (SELECT code FROM Ros_references.CL_PROCESSING_TYPES cl WHERE cl.id = processing_type_id);
ALTER TABLE ONLY ros_common.estimated_weights ADD CONSTRAINT fk_ros_common_processing_type_code_estimated_weights FOREIGN KEY (processing_type_code) REFERENCES refs_fishery.FISH_PROCESSING_TYPES(code);
ALTER TABLE ros_common.measured_weights ADD COLUMN processing_type_code CHAR(2);
UPDATE ros_common.measured_weights SET processing_type_code = (SELECT code FROM Ros_references.CL_PROCESSING_TYPES cl WHERE cl.id = processing_type_id);
ALTER TABLE ONLY ros_common.measured_weights ADD CONSTRAINT fk_ros_common_processing_type_code_measured_weights FOREIGN KEY (processing_type_code) REFERENCES refs_fishery.FISH_PROCESSING_TYPES(code);
ALTER TABLE ros_common.species_by_product_type ADD COLUMN processing_type_code CHAR(2);
UPDATE ros_common.species_by_product_type SET processing_type_code = (SELECT code FROM Ros_references.CL_PROCESSING_TYPES cl WHERE cl.id = processing_type_id);
ALTER TABLE ONLY ros_common.species_by_product_type ADD CONSTRAINT fk_ros_common_processing_type_code_species_by_product_type FOREIGN KEY (processing_type_code) REFERENCES refs_fishery.FISH_PROCESSING_TYPES(code);
ALTER TABLE ros_gn.gn_hauling_operations ADD COLUMN sampling_protocol_code CHAR(2);
UPDATE ros_gn.gn_hauling_operations SET sampling_protocol_code = (SELECT code FROM refs_biological.SAMPLING_PROTOCOLS WHERE code_orig = (SELECT code FROM ROS_references.CL_SAMPLING_PROTOCOLS cl WHERE cl.id = sampling_protocol_id));
ALTER TABLE ONLY ros_gn.gn_hauling_operations ADD CONSTRAINT fk_ros_gn_sampling_protocol_code_gn_hauling_operations FOREIGN KEY (sampling_protocol_code) REFERENCES refs_biological.SAMPLING_PROTOCOLS(code);
ALTER TABLE ros_ll.ll_hauling_operations ADD COLUMN sampling_protocol_code CHAR(2);
UPDATE ros_ll.ll_hauling_operations SET sampling_protocol_code = (SELECT code FROM refs_biological.SAMPLING_PROTOCOLS WHERE code_orig = (SELECT code FROM ROS_references.CL_SAMPLING_PROTOCOLS cl WHERE cl.id = sampling_protocol_id));
ALTER TABLE ONLY ros_ll.ll_hauling_operations ADD CONSTRAINT fk_ros_ll_sampling_protocol_code_ll_hauling_operations FOREIGN KEY (sampling_protocol_code) REFERENCES refs_biological.SAMPLING_PROTOCOLS(code);
ALTER TABLE ros_pl.bait_fishing_operations ADD COLUMN sampling_protocol_code CHAR(2);
UPDATE ros_pl.bait_fishing_operations SET sampling_protocol_code = (SELECT code FROM refs_biological.SAMPLING_PROTOCOLS WHERE code_orig = (SELECT code FROM ROS_references.CL_SAMPLING_PROTOCOLS cl WHERE cl.id = sampling_protocol_id));
ALTER TABLE ONLY ros_pl.bait_fishing_operations ADD CONSTRAINT fk_ros_pl_sampling_protocol_code_bait_fishing_operations FOREIGN KEY (sampling_protocol_code) REFERENCES refs_biological.SAMPLING_PROTOCOLS(code);
ALTER TABLE ros_pl.pl_tuna_fishing_operations ADD COLUMN sampling_protocol_code CHAR(2);
UPDATE ros_pl.pl_tuna_fishing_operations SET sampling_protocol_code = (SELECT code FROM refs_biological.SAMPLING_PROTOCOLS WHERE code_orig = (SELECT code FROM ROS_references.CL_SAMPLING_PROTOCOLS cl WHERE cl.id = sampling_protocol_id));
ALTER TABLE ONLY ros_pl.pl_tuna_fishing_operations ADD CONSTRAINT fk_ros_pl_sampling_protocol_code_pl_tuna_fishing_operations FOREIGN KEY (sampling_protocol_code) REFERENCES refs_biological.SAMPLING_PROTOCOLS(code);
ALTER TABLE ros_common.depredation_details ADD COLUMN depredation_source_code VARCHAR(3);
UPDATE ros_common.depredation_details SET depredation_source_code = (SELECT code FROM ROS_references.CL_SCARS cl WHERE cl.id = depredation_source_id);
ALTER TABLE ONLY ros_common.depredation_details ADD CONSTRAINT fk_ros_common_depredation_source_code_depredation_details FOREIGN KEY (depredation_source_code) REFERENCES refs_biological.SCARS(code);
ALTER TABLE ros_ps.ps_setting_operations ADD COLUMN first_school_detection_method_code CHAR(2);
UPDATE ros_ps.ps_setting_operations SET first_school_detection_method_code = (SELECT code FROM refs_fishery.SCHOOL_DETECTION_METHODS WHERE code_orig = (SELECT code FROM ROS_references.CL_SCHOOL_DETECTION_METHODS cl WHERE cl.id = first_school_detection_method_id));
ALTER TABLE ONLY ros_ps.ps_setting_operations ADD CONSTRAINT fk_ros_ps_first_school_detection_method_code_ps_setting_operations FOREIGN KEY (first_school_detection_method_code) REFERENCES refs_fishery.SCHOOL_DETECTION_METHODS(code);
ALTER TABLE ros_pl.bait_fishing_operations_cl_school_sighting_cues ADD COLUMN school_sighting_cue_code CHAR(2);
UPDATE ros_pl.bait_fishing_operations_cl_school_sighting_cues SET school_sighting_cue_code = (SELECT code FROM refs_fishery.SCHOOL_SIGHTING_CUES WHERE code_orig = (SELECT code FROM Ros_references.CL_SCHOOL_SIGHTING_CUES cl WHERE cl.id = school_sighting_cue_id));
ALTER TABLE ros_pl.bait_fishing_operations_cl_school_sighting_cues ALTER COLUMN school_sighting_cue_code SET NOT NULL;
ALTER TABLE ONLY ros_pl.bait_fishing_operations_cl_school_sighting_cues ADD CONSTRAINT fk_ros_pl_school_sighting_cue_code_bait_fishing_operations_cl_school_sighting_cues FOREIGN KEY (school_sighting_cue_code) REFERENCES refs_fishery.SCHOOL_SIGHTING_CUES(code);
ALTER TABLE ros_pl.pl_tuna_fishing_operations_cl_school_sighting_cues ADD COLUMN school_sighting_cue_code CHAR(2);
UPDATE ros_pl.pl_tuna_fishing_operations_cl_school_sighting_cues SET school_sighting_cue_code = (SELECT code FROM refs_fishery.SCHOOL_SIGHTING_CUES WHERE code_orig = (SELECT code FROM Ros_references.CL_SCHOOL_SIGHTING_CUES cl WHERE cl.id = school_sighting_cue_id));
ALTER TABLE ros_pl.pl_tuna_fishing_operations_cl_school_sighting_cues ALTER COLUMN school_sighting_cue_code SET NOT NULL;
ALTER TABLE ONLY ros_pl.pl_tuna_fishing_operations_cl_school_sighting_cues ADD CONSTRAINT fk_ros_pl_school_sighting_cue_code_pl_tuna_fishing_operations_cl_school_sighting_cues FOREIGN KEY (school_sighting_cue_code) REFERENCES refs_fishery.SCHOOL_SIGHTING_CUES(code);
ALTER TABLE ros_ps.ps_setting_operations_cl_school_sighting_cues ADD COLUMN school_sighting_cue_code CHAR(2);
UPDATE ros_ps.ps_setting_operations_cl_school_sighting_cues SET school_sighting_cue_code = (SELECT code FROM refs_fishery.SCHOOL_SIGHTING_CUES WHERE code_orig = (SELECT code FROM Ros_references.CL_SCHOOL_SIGHTING_CUES cl WHERE cl.id = school_sighting_cue_id));
ALTER TABLE ros_ps.ps_setting_operations_cl_school_sighting_cues ALTER COLUMN school_sighting_cue_code SET NOT NULL;
ALTER TABLE ONLY ros_ps.ps_setting_operations_cl_school_sighting_cues ADD CONSTRAINT fk_ros_ps_school_sighting_cue_code_ps_setting_operations_cl_school_sighting_cues FOREIGN KEY (school_sighting_cue_code) REFERENCES refs_fishery.SCHOOL_SIGHTING_CUES(code);
ALTER TABLE ros_common.biometric_information ADD COLUMN sex_code CHAR(1);
UPDATE ros_common.biometric_information SET sex_code = (SELECT code FROM refs_biological.SEX WHERE code_orig = (SELECT code FROM Ros_references.CL_SEXES cl WHERE cl.id = sex_id));
ALTER TABLE ONLY ros_common.biometric_information ADD CONSTRAINT fk_ros_common_sex_code_biometric_information FOREIGN KEY (sex_code) REFERENCES refs_biological.SEX(code);
ALTER TABLE ros_gn.sinkers_by_type ADD COLUMN sinker_material_type_code CHAR(2);
UPDATE ros_gn.sinkers_by_type SET sinker_material_type_code = (SELECT code FROM refs_fishery.SINKER_MATERIAL_TYPES WHERE code_orig = (SELECT code FROM ROS_references.CL_SINKER_MATERIAL_TYPES cl WHERE cl.id = sinker_material_type_id));
ALTER TABLE ONLY ros_gn.sinkers_by_type ADD CONSTRAINT fk_ros_gn_sinker_material_type_code_sinkers_by_type FOREIGN KEY (sinker_material_type_code) REFERENCES refs_fishery.SINKER_MATERIAL_TYPES(code);
ALTER TABLE ros_ll.ll_hauling_operations_stunning_methods ADD COLUMN stunning_method_code CHAR(2);
UPDATE ros_ll.ll_hauling_operations_stunning_methods SET stunning_method_code = (SELECT code FROM refs_fishery.STUNNING_METHODS WHERE code_orig = (SELECT code FROM Ros_references.CL_STUNNING_METHODS cl WHERE cl.id = stunning_method_id));
ALTER TABLE ros_ll.ll_hauling_operations_stunning_methods ALTER COLUMN stunning_method_code SET NOT NULL;
ALTER TABLE ONLY ros_ll.ll_hauling_operations_stunning_methods ADD CONSTRAINT fk_ros_ll_stunning_method_code_ll_hauling_operations_stunning_methods FOREIGN KEY (stunning_method_code) REFERENCES refs_fishery.STUNNING_METHODS(code);
ALTER TABLE ros_gn.gn_tag_details ADD COLUMN tag_type_code CHAR(2);
UPDATE ros_gn.gn_tag_details SET tag_type_code = (SELECT code FROM refs_biological.TAG_TYPES WHERE code_orig = (SELECT code FROM ROS_references.CL_TAG_TYPES cl WHERE cl.id = tag_type_id));
ALTER TABLE ONLY ros_gn.gn_tag_details ADD CONSTRAINT fk_ros_gn_tag_type_code_gn_tag_details FOREIGN KEY (tag_type_code) REFERENCES refs_biological.TAG_TYPES(code);
ALTER TABLE ros_ll.ll_tag_details ADD COLUMN tag_type_code CHAR(2);
UPDATE ros_ll.ll_tag_details SET tag_type_code = (SELECT code FROM refs_biological.TAG_TYPES WHERE code_orig = (SELECT code FROM ROS_references.CL_TAG_TYPES cl WHERE cl.id = tag_type_id));
ALTER TABLE ONLY ros_ll.ll_tag_details ADD CONSTRAINT fk_ros_ll_tag_type_code_ll_tag_details FOREIGN KEY (tag_type_code) REFERENCES refs_biological.TAG_TYPES(code);
ALTER TABLE ros_pl.pl_tag_details ADD COLUMN tag_type_code CHAR(2);
UPDATE ros_pl.pl_tag_details SET tag_type_code = (SELECT code FROM refs_biological.TAG_TYPES WHERE code_orig = (SELECT code FROM ROS_references.CL_TAG_TYPES cl WHERE cl.id = tag_type_id));
ALTER TABLE ONLY ros_pl.pl_tag_details ADD CONSTRAINT fk_ros_pl_tag_type_code_pl_tag_details FOREIGN KEY (tag_type_code) REFERENCES refs_biological.TAG_TYPES(code);
ALTER TABLE ros_ps.ps_tag_details ADD COLUMN tag_type_code CHAR(2);
UPDATE ros_ps.ps_tag_details SET tag_type_code = (SELECT code FROM refs_biological.TAG_TYPES WHERE code_orig = (SELECT code FROM ROS_references.CL_TAG_TYPES cl WHERE cl.id = tag_type_id));
ALTER TABLE ONLY ros_ps.ps_tag_details ADD CONSTRAINT fk_ros_ps_tag_type_code_ps_tag_details FOREIGN KEY (tag_type_code) REFERENCES refs_biological.TAG_TYPES(code);
ALTER TABLE ros_common.waste_managements ADD COLUMN waste_category_code CHAR(2);
UPDATE ros_common.waste_managements SET waste_category_code = (SELECT code FROM ROS_references.CL_WASTE_CATEGORIES cl WHERE cl.id = waste_category_id);
ALTER TABLE ONLY ros_common.waste_managements ADD CONSTRAINT fk_ros_common_waste_category_code_waste_managements FOREIGN KEY (waste_category_code) REFERENCES refs_fishery.WASTE_CATEGORIES(code);
ALTER TABLE ros_common.estimated_weights ADD COLUMN weight_estimation_method_code CHAR(2);
UPDATE ros_common.estimated_weights SET weight_estimation_method_code = (SELECT code FROM ROS_references.CL_WEIGHT_ESTIMATION_METHODS cl WHERE cl.id = weight_estimation_method_id);
UPDATE ros_common.estimated_weights SET type_of_measurement_code = 'WG';
ALTER TABLE ONLY ros_common.estimated_weights ADD CONSTRAINT fk_ros_common_weight_estimation_method_code_estimated_weights FOREIGN KEY (weight_estimation_method_code, type_of_measurement_code) REFERENCES refs_biological.MEASUREMENT_TOOLS(code, type_of_measurement_code);
ALTER TABLE ros_pl.bait_fishing_operations ADD COLUMN wind_scale_code CHAR(2);
UPDATE ros_pl.bait_fishing_operations SET wind_scale_code = (SELECT code FROM Ros_references.CL_WIND_SCALES cl WHERE cl.id = wind_scale_id);
ALTER TABLE ONLY ros_pl.bait_fishing_operations ADD CONSTRAINT fk_ros_pl_wind_scale_code_bait_fishing_operations FOREIGN KEY (wind_scale_code) REFERENCES refs_fishery.WIND_SCALES(code);
ALTER TABLE ros_pl.pl_tuna_fishing_operations ADD COLUMN wind_scale_code CHAR(2);
UPDATE ros_pl.pl_tuna_fishing_operations SET wind_scale_code = (SELECT code FROM Ros_references.CL_WIND_SCALES cl WHERE cl.id = wind_scale_id);
ALTER TABLE ONLY ros_pl.pl_tuna_fishing_operations ADD CONSTRAINT fk_ros_pl_wind_scale_code_pl_tuna_fishing_operations FOREIGN KEY (wind_scale_code) REFERENCES refs_fishery.WIND_SCALES(code);
ALTER TABLE ros_ps.ps_setting_operations ADD COLUMN wind_scale_code CHAR(2);
UPDATE ros_ps.ps_setting_operations SET wind_scale_code = (SELECT code FROM Ros_references.CL_WIND_SCALES cl WHERE cl.id = wind_scale_id);
ALTER TABLE ONLY ros_ps.ps_setting_operations ADD CONSTRAINT fk_ros_ps_wind_scale_code_ps_setting_operations FOREIGN KEY (wind_scale_code) REFERENCES refs_fishery.WIND_SCALES(code);
ALTER TABLE ros_common.vessel_attributes_fish_storage_type DROP COLUMN fish_storage_type_id;
ALTER TABLE ros_gn.gillnet_configuration DROP COLUMN float_type_id;
ALTER TABLE ros_gn.gillnet_configuration DROP COLUMN gillnet_material_type_id;
ALTER TABLE ros_common.activity_details DROP COLUMN activity_id;
ALTER TABLE ros_pl.baits_and_conditions DROP COLUMN bait_condition_id;
ALTER TABLE ros_ll.baits_by_conditions DROP COLUMN bait_condition_id;
ALTER TABLE ros_ll.ll_additional_catch_details_on_ssi DROP COLUMN bait_condition_id;
ALTER TABLE ros_pl.bait_fishing_operations DROP COLUMN bait_fishing_method_id;
ALTER TABLE ros_pl.bait_fishing_operations DROP COLUMN bait_school_detection_method_id;
ALTER TABLE ros_common.biometric_information DROP COLUMN bio_collection_sampling_method_id;
ALTER TABLE ros_gn.gn_catch_details DROP COLUMN estimated_weight_sampling_method_id;
ALTER TABLE ros_ll.ll_catch_details DROP COLUMN estimated_weight_sampling_method_id;
ALTER TABLE ros_pl.pl_catch_details DROP COLUMN estimated_weight_sampling_method_id;
ALTER TABLE ros_ps.ps_catch_details DROP COLUMN estimated_weight_sampling_method_id;
ALTER TABLE ros_common.carrier_vessel_identification DROP COLUMN vessel_flag_id;
ALTER TABLE ros_common.iotc_person_contact_details DROP COLUMN nationality_id;
ALTER TABLE ros_common.iotc_person_details DROP COLUMN nationality_id;
ALTER TABLE ros_common.locations DROP COLUMN country_id;
ALTER TABLE ros_common.person_contact_details DROP COLUMN nationality_id;
ALTER TABLE ros_common.person_details DROP COLUMN nationality_id;
ALTER TABLE ros_ll.ll_additional_catch_details_on_ssi DROP COLUMN dehooker_device_id;
ALTER TABLE ros_common.waste_managements DROP COLUMN waste_storage_or_disposal_method_id;
ALTER TABLE ros_ps.ps_object_details DROP COLUMN fad_raft_design_id;
ALTER TABLE ros_ps.ps_object_details DROP COLUMN fad_tail_design_id;
ALTER TABLE ros_gn.gn_catch_details DROP COLUMN fates_id;
ALTER TABLE ros_pl.pl_catch_details DROP COLUMN fates_id;
ALTER TABLE ros_common.vessel_attributes_fish_preservation_method DROP COLUMN fish_preservation_method_id;
ALTER TABLE ros_gn.gn_additional_catch_details_on_ssi DROP COLUMN gear_interaction_id;
ALTER TABLE ros_ll.ll_additional_catch_details_on_ssi DROP COLUMN gear_interaction_id;
ALTER TABLE ros_pl.pl_additional_catch_details_on_ssi DROP COLUMN gear_interaction_id;
ALTER TABLE ros_ps.ps_additional_catch_details_on_ssi DROP COLUMN gear_interaction_id;
ALTER TABLE ros_gn.gn_additional_catch_details_on_ssi DROP COLUMN handling_method_id;
ALTER TABLE ros_ll.ll_additional_catch_details_on_ssi DROP COLUMN handling_method_id;
ALTER TABLE ros_pl.pl_additional_catch_details_on_ssi DROP COLUMN handling_method_id;
ALTER TABLE ros_ps.ps_additional_catch_details_on_ssi DROP COLUMN handling_method_id;
ALTER TABLE ros_ll.hooks_by_type DROP COLUMN hook_type_id;
ALTER TABLE ros_pl.lures_or_jiggers_by_type DROP COLUMN hook_type_id;
ALTER TABLE ros_pl.pl_general_gear_attributes DROP COLUMN hook_type_id;
ALTER TABLE ros_common.vessel_attributes DROP COLUMN hull_material_id;
ALTER TABLE ros_common.measured_lengths DROP COLUMN length_measuring_tool_id;
ALTER TABLE ros_ll.lights_by_type_and_colour DROP COLUMN light_colour_id;
ALTER TABLE ros_ll.lights_by_type_and_colour DROP COLUMN light_type_id;
ALTER TABLE ros_ll.branchline_sections DROP COLUMN branchline_material_type_id;
ALTER TABLE ros_ll.ll_additional_catch_details_on_ssi DROP COLUMN leader_material_type_id;
ALTER TABLE ros_ll.ll_general_gear_attributes DROP COLUMN line_material_type_id;
ALTER TABLE ros_gn.gn_mitigation_measures_mitigation_devices DROP COLUMN mitigation_device_id;
ALTER TABLE ros_ll.ll_gear_specifications_mitigation_device DROP COLUMN mitigation_device_id;
ALTER TABLE ros_ll.ll_mitigation_measures_mitigation_devices DROP COLUMN mitigation_device_id;
ALTER TABLE ros_gn.gn_gillnet_configuration_net_web_colours DROP COLUMN net_colour_id;
ALTER TABLE ros_gn.gn_hauling_operations DROP COLUMN net_condition_id;
ALTER TABLE ros_gn.gn_setting_operations DROP COLUMN net_configuration_id;
ALTER TABLE ros_gn.gn_setting_operations DROP COLUMN net_deploy_depth_id;
ALTER TABLE ros_gn.gn_setting_operations DROP COLUMN net_setting_strategy_id;
ALTER TABLE ros_common.carrier_vessel_identification DROP COLUMN vessel_registration_port_id;
ALTER TABLE ros_common.vessel_identification DROP COLUMN port_id;
ALTER TABLE ros_common.measured_weights DROP COLUMN processing_type_id;
ALTER TABLE ros_common.species_by_product_type DROP COLUMN processing_type_id;
ALTER TABLE ros_gn.gn_hauling_operations DROP COLUMN sampling_protocol_id;
ALTER TABLE ros_ll.ll_hauling_operations DROP COLUMN sampling_protocol_id;
ALTER TABLE ros_pl.bait_fishing_operations DROP COLUMN sampling_protocol_id;
ALTER TABLE ros_pl.pl_tuna_fishing_operations DROP COLUMN sampling_protocol_id;
ALTER TABLE ros_common.depredation_details DROP COLUMN depredation_source_id;
ALTER TABLE ros_ps.ps_setting_operations DROP COLUMN first_school_detection_method_id;
ALTER TABLE ros_pl.bait_fishing_operations_cl_school_sighting_cues DROP COLUMN school_sighting_cue_id;
ALTER TABLE ros_pl.pl_tuna_fishing_operations_cl_school_sighting_cues DROP COLUMN school_sighting_cue_id;
ALTER TABLE ros_ps.ps_setting_operations_cl_school_sighting_cues DROP COLUMN school_sighting_cue_id;
ALTER TABLE ros_gn.sinkers_by_type DROP COLUMN sinker_material_type_id;
ALTER TABLE ros_common.depredation_details DROP COLUMN predator_observed_id;
ALTER TABLE ros_common.species_by_product_type DROP COLUMN species_id;
ALTER TABLE ros_gn.gn_catch_details DROP COLUMN species_id;
ALTER TABLE ros_ll.baits_by_conditions DROP COLUMN species_id;
ALTER TABLE ros_ll.ll_setting_operations_target_species DROP COLUMN target_species_id;
ALTER TABLE ros_pl.baits_and_conditions DROP COLUMN species_id;
ALTER TABLE ros_pl.pl_catch_details DROP COLUMN species_id;
ALTER TABLE ros_pl.pl_tuna_fishing_operations_target_species DROP COLUMN target_species_id;
ALTER TABLE ros_ps.cetaceans_whale_shark_sightings DROP COLUMN species_id;
ALTER TABLE ros_ll.ll_hauling_operations_stunning_methods DROP COLUMN stunning_method_id;
ALTER TABLE ros_gn.gn_tag_details DROP COLUMN tag_type_id;
ALTER TABLE ros_ll.ll_tag_details DROP COLUMN tag_type_id;
ALTER TABLE ros_pl.pl_tag_details DROP COLUMN tag_type_id;
ALTER TABLE ros_ps.ps_tag_details DROP COLUMN tag_type_id;
ALTER TABLE ros_common.waste_managements DROP COLUMN waste_category_id;
ALTER TABLE ros_pl.bait_fishing_operations DROP COLUMN wind_scale_id;
ALTER TABLE ros_pl.pl_tuna_fishing_operations DROP COLUMN wind_scale_id;
ALTER TABLE ros_ps.ps_setting_operations DROP COLUMN wind_scale_id;
ALTER TABLE ros_common.vessel_identification DROP COLUMN main_fishing_gear_id;
ALTER TABLE ros_common.observer_identification DROP COLUMN nationality_id;
ALTER TABLE ros_common.vessel_identification DROP COLUMN flag_id;
ALTER TABLE ros_gn.gn_observer_data DROP COLUMN reporting_country_id;
ALTER TABLE ros_ll.ll_observer_data DROP COLUMN reporting_country_id;
ALTER TABLE ros_pl.pl_observer_data DROP COLUMN reporting_country_id;
ALTER TABLE ros_ps.ps_observer_data DROP COLUMN reporting_country_id;
ALTER TABLE ros_ll.ll_catch_details DROP COLUMN fates_id;
ALTER TABLE ros_ps.ps_catch_details DROP COLUMN fates_id;
ALTER TABLE ros_common.additional_details_on_non_target_species DROP COLUMN condition_at_capture_id;
ALTER TABLE ros_common.additional_details_on_non_target_species DROP COLUMN condition_at_release_id;
ALTER TABLE ros_common.measured_lengths DROP COLUMN measured_length_type_id;
ALTER TABLE ros_common.estimated_weights DROP COLUMN processing_type_id;
ALTER TABLE ros_common.estimated_weights DROP COLUMN weight_estimation_method_id;
ALTER TABLE ros_common.biometric_information DROP COLUMN sex_id;
ALTER TABLE ros_meta.ros_observers_2_flags DROP COLUMN flag_id;
ALTER TABLE ros_meta.ros_observers DROP COLUMN nationality_id;
ALTER TABLE ros_references.cl_ports DROP COLUMN country_id;
DROP TABLE ROS_references.cl_fishing_ground_types;
DROP TABLE Ros_references.CL_SCHOOL_TYPE_CATEGORIES;
DROP TABLE ROS_references.CL_FISH_STORAGE_TYPES;
DROP TABLE ROS_references.CL_FLOAT_TYPES;
DROP TABLE Ros_references.CL_GILLNET_MATERIAL_TYPES;
DROP TABLE ROS_references.CL_ACTIVITIES;
DROP TABLE ROS_references.CL_BAIT_CONDITIONS;
DROP TABLE ROS_references.CL_BAIT_FISHING_METHODS;
DROP TABLE ROS_references.CL_BAIT_SCHOOL_DETECTION_METHODS;
DROP TABLE ROS_references.CL_BIO_COLLECTION_SAMPLING_METHODS;
DROP TABLE Ros_references.CL_CATCH_ESTIMATES_SAMPLING_METHODS;
DROP TABLE ROS_references.CL_DEHOOKER_DEVICES;
DROP TABLE ROS_references.CL_DISPOSAL_METHODS;
DROP TABLE ROS_references.CL_FAD_RAFT_DESIGNS;
DROP TABLE ROS_references.CL_FAD_TAIL_DESIGNS;
DROP TABLE ROS_references.CL_FISH_PRESERVATION_METHODS;
DROP TABLE ROS_references.CL_GEAR_INTERACTIONS;
DROP TABLE ROS_references.CL_HANDLING_METHODS;
DROP TABLE Ros_references.CL_HULL_MATERIALS;
DROP TABLE ROS_references.CL_LENGTH_MEASURING_TOOLS;
DROP TABLE ROS_references.CL_LIGHT_COLOURS;
DROP TABLE ROS_references.CL_LIGHT_TYPES;
DROP TABLE ROS_references.CL_LINE_MATERIAL_TYPES;
DROP TABLE ROS_references.CL_MITIGATION_DEVICES;
DROP TABLE ROS_references.CL_NET_COLOURS;
DROP TABLE ROS_references.CL_NET_CONDITIONS;
DROP TABLE ROS_references.CL_NET_CONFIGURATIONS;
DROP TABLE Ros_references.CL_NET_DEPLOY_DEPTHS;
DROP TABLE ROS_references.CL_NET_SETTING_STRATEGIES;
DROP TABLE ROS_references.CL_SAMPLING_PROTOCOLS;
DROP TABLE ROS_references.CL_SCARS;
DROP TABLE ROS_references.CL_SCHOOL_DETECTION_METHODS;
DROP TABLE Ros_references.CL_SCHOOL_SIGHTING_CUES;
DROP TABLE ROS_references.CL_SINKER_MATERIAL_TYPES;
DROP TABLE Ros_references.CL_STUNNING_METHODS;
DROP TABLE ROS_references.CL_TAG_TYPES;
DROP TABLE ROS_references.CL_WASTE_CATEGORIES;
DROP TABLE Ros_references.CL_WIND_SCALES;
DROP TABLE ROS_analysis.FLAG_TO_FLEET;
DROP TABLE Ros_references.CL_GEAR_TYPES;
DROP TABLE Ros_references.CL_FATES;
DROP TABLE Ros_references.CL_HOOKS;
DROP TABLE ROS_references.CL_INCIDENTAL_CAPTURES_CONDITIONS;
DROP TABLE Ros_references.CL_LENGTH_MEASUREMENT_TYPES;
DROP TABLE Ros_references.CL_PROCESSING_TYPES;
DROP TABLE Ros_references.CL_SEXES;
DROP TABLE ROS_references.CL_WEIGHT_ESTIMATION_METHODS;
DROP TABLE ROS_references.CL_COUNTRIES;
-- ALTER TABLE ros_common.carrier_vessel_identification ADD COLUMN vessel_registration_port_code VARCHAR(16);
-- UPDATE ros_common.carrier_vessel_identification SET vessel_registration_port_code = (SELECT code FROM Ros_references.CL_PORTS cl WHERE cl.id = vessel_registration_port_id);
-- ALTER TABLE ONLY ros_common.carrier_vessel_identification ADD CONSTRAINT fk_ros_common_vessel_registration_port_code_carrier_vessel_identification FOREIGN KEY (vessel_registration_port_code) REFERENCES refs_admin.PORTS(code);
-- ALTER TABLE ros_common.vessel_identification ADD COLUMN port_code VARCHAR(16);
-- UPDATE ros_common.vessel_identification SET port_code = (SELECT code FROM Ros_references.CL_PORTS cl WHERE cl.id = port_id);
-- ALTER TABLE ONLY ros_common.vessel_identification ADD CONSTRAINT fk_ros_common_port_code_vessel_identification FOREIGN KEY (port_code) REFERENCES refs_admin.PORTS(code);
-- ALTER TABLE ros_common.vessel_trip_details ADD COLUMN departure_port_code VARCHAR(16);
-- UPDATE ros_common.vessel_trip_details SET departure_port_code = (SELECT code FROM Ros_references.CL_PORTS cl WHERE cl.id = departure_port_id);
-- ALTER TABLE ONLY ros_common.vessel_trip_details ADD CONSTRAINT fk_ros_common_departure_port_code_vessel_trip_details FOREIGN KEY (departure_port_code) REFERENCES refs_admin.PORTS(code);
-- ALTER TABLE ros_common.vessel_trip_details ADD COLUMN return_port_code VARCHAR(16);
-- UPDATE ros_common.vessel_trip_details SET return_port_code = (SELECT code FROM Ros_references.CL_PORTS cl WHERE cl.id = return_port_id);
-- ALTER TABLE ONLY ros_common.vessel_trip_details ADD CONSTRAINT fk_ros_common_return_port_code_vessel_trip_details FOREIGN KEY (return_port_code) REFERENCES refs_admin.PORTS(code);
-- ALTER TABLE ros_common.depredation_details ADD COLUMN predator_observed_code VARCHAR(16);
-- UPDATE ros_common.depredation_details SET predator_observed_code = (SELECT code FROM Ros_references.CL_SPECIES cl WHERE cl.id = predator_observed_id);
-- ALTER TABLE ONLY ros_common.depredation_details ADD CONSTRAINT fk_ros_common_predator_observed_code_depredation_details FOREIGN KEY (predator_observed_code) REFERENCES refs_biological.SPECIES(code);
-- ALTER TABLE ros_common.species_by_product_type ADD COLUMN species_code VARCHAR(16);
-- UPDATE ros_common.species_by_product_type SET species_code = (SELECT code FROM Ros_references.CL_SPECIES cl WHERE cl.id = species_id);
-- ALTER TABLE ONLY ros_common.species_by_product_type ADD CONSTRAINT fk_ros_common_species_code_species_by_product_type FOREIGN KEY (species_code) REFERENCES refs_biological.SPECIES(code);
-- ALTER TABLE ros_common.vessel_identification_licensed_target_species ADD COLUMN licensed_target_species_code VARCHAR(16);
-- UPDATE ros_common.vessel_identification_licensed_target_species SET licensed_target_species_code = (SELECT code FROM Ros_references.CL_SPECIES cl WHERE cl.id = licensed_target_species_id);
-- ALTER TABLE ros_common.vessel_identification_licensed_target_species ALTER COLUMN licensed_target_species_code SET NOT NULL;
-- ALTER TABLE ONLY ros_common.vessel_identification_licensed_target_species ADD CONSTRAINT fk_ros_common_licensed_target_species_code_vessel_identification_licensed_target_species FOREIGN KEY (licensed_target_species_code) REFERENCES refs_biological.SPECIES(code);
-- ALTER TABLE ros_gn.gn_catch_details ADD COLUMN species_code VARCHAR(16);
-- UPDATE ros_gn.gn_catch_details SET species_code = (SELECT code FROM Ros_references.CL_SPECIES cl WHERE cl.id = species_id);
-- ALTER TABLE ONLY ros_gn.gn_catch_details ADD CONSTRAINT fk_ros_gn_species_code_gn_catch_details FOREIGN KEY (species_code) REFERENCES refs_biological.SPECIES(code);
-- ALTER TABLE ros_ll.baits_by_conditions ADD COLUMN species_code VARCHAR(16);
-- UPDATE ros_ll.baits_by_conditions SET species_code = (SELECT code FROM Ros_references.CL_SPECIES cl WHERE cl.id = species_id);
-- ALTER TABLE ONLY ros_ll.baits_by_conditions ADD CONSTRAINT fk_ros_ll_species_code_baits_by_conditions FOREIGN KEY (species_code) REFERENCES refs_biological.SPECIES(code);
-- ALTER TABLE ros_ll.ll_catch_details ADD COLUMN species_code VARCHAR(16);
-- UPDATE ros_ll.ll_catch_details SET species_code = (SELECT code FROM Ros_references.CL_SPECIES cl WHERE cl.id = species_id);
-- ALTER TABLE ONLY ros_ll.ll_catch_details ADD CONSTRAINT fk_ros_ll_species_code_ll_catch_details FOREIGN KEY (species_code) REFERENCES refs_biological.SPECIES(code);
-- ALTER TABLE ros_ll.ll_setting_operations_target_species ADD COLUMN target_species_code VARCHAR(16);
-- UPDATE ros_ll.ll_setting_operations_target_species SET target_species_code = (SELECT code FROM Ros_references.CL_SPECIES cl WHERE cl.id = target_species_id);
-- ALTER TABLE ros_ll.ll_setting_operations_target_species ALTER COLUMN target_species_code SET NOT NULL;
-- ALTER TABLE ONLY ros_ll.ll_setting_operations_target_species ADD CONSTRAINT fk_ros_ll_target_species_code_ll_setting_operations_target_species FOREIGN KEY (target_species_code) REFERENCES refs_biological.SPECIES(code);
-- ALTER TABLE ros_pl.baits_and_conditions ADD COLUMN species_code VARCHAR(16);
-- UPDATE ros_pl.baits_and_conditions SET species_code = (SELECT code FROM Ros_references.CL_SPECIES cl WHERE cl.id = species_id);
-- ALTER TABLE ONLY ros_pl.baits_and_conditions ADD CONSTRAINT fk_ros_pl_species_code_baits_and_conditions FOREIGN KEY (species_code) REFERENCES refs_biological.SPECIES(code);
-- ALTER TABLE ros_pl.pl_catch_details ADD COLUMN species_code VARCHAR(16);
-- UPDATE ros_pl.pl_catch_details SET species_code = (SELECT code FROM Ros_references.CL_SPECIES cl WHERE cl.id = species_id);
-- ALTER TABLE ONLY ros_pl.pl_catch_details ADD CONSTRAINT fk_ros_pl_species_code_pl_catch_details FOREIGN KEY (species_code) REFERENCES refs_biological.SPECIES(code);
-- ALTER TABLE ros_pl.pl_tuna_fishing_operations_target_species ADD COLUMN target_species_code VARCHAR(16);
-- UPDATE ros_pl.pl_tuna_fishing_operations_target_species SET target_species_code = (SELECT code FROM Ros_references.CL_SPECIES cl WHERE cl.id = target_species_id);
-- ALTER TABLE ros_pl.pl_tuna_fishing_operations_target_species ALTER COLUMN target_species_code SET NOT NULL;
-- ALTER TABLE ONLY ros_pl.pl_tuna_fishing_operations_target_species ADD CONSTRAINT fk_ros_pl_target_species_code_pl_tuna_fishing_operations_target_species FOREIGN KEY (target_species_code) REFERENCES refs_biological.SPECIES(code);
-- ALTER TABLE ros_ps.cetaceans_whale_shark_sightings ADD COLUMN species_code VARCHAR(16);
-- UPDATE ros_ps.cetaceans_whale_shark_sightings SET species_code = (SELECT code FROM Ros_references.CL_SPECIES cl WHERE cl.id = species_id);
-- ALTER TABLE ONLY ros_ps.cetaceans_whale_shark_sightings ADD CONSTRAINT fk_ros_ps_species_code_cetaceans_whale_shark_sightings FOREIGN KEY (species_code) REFERENCES refs_biological.SPECIES(code);
-- ALTER TABLE ros_ps.ps_catch_details ADD COLUMN species_code VARCHAR(16);
-- UPDATE ros_ps.ps_catch_details SET species_code = (SELECT code FROM Ros_references.CL_SPECIES cl WHERE cl.id = species_id);
-- ALTER TABLE ONLY ros_ps.ps_catch_details ADD CONSTRAINT fk_ros_ps_species_code_ps_catch_details FOREIGN KEY (species_code) REFERENCES refs_biological.SPECIES(code);
-- ALTER TABLE ros_common.vessel_trip_details DROP COLUMN departure_port_id;
-- ALTER TABLE ros_common.vessel_trip_details DROP COLUMN return_port_id;
-- ALTER TABLE ros_common.vessel_identification_licensed_target_species DROP COLUMN licensed_target_species_id;
-- ALTER TABLE ros_ll.ll_catch_details DROP COLUMN species_id;
-- ALTER TABLE ros_ps.ps_catch_details DROP COLUMN species_id;
-- DROP TABLE Ros_references.CL_PORTS;
-- DROP TABLE Ros_references.CL_SPECIES;
COMMIT TRANSACTION;